### ISSUE TITLE
Add method for getting next language

### ISSUE THREAD

**Issue by boruok** [Insality/defold-lang#3]
Is possible to add new method for getting next lang?

current workaround is
```lua
local get_next_lang = function()
	local langs = lang.get_langs()
	for i, _ in ipairs(langs) do
		if langs[i] == lang.get_lang() then
			return langs[(i % #langs) + 1]
		end
	end
end
```

**Comment by Insality** [comment]
Sounds neat to add it. Can be useful for some cases

**Comment by Insality** [comment]
Solver in release 3
https://github.com/Insality/defold-lang/archive/refs/tags/3.zip
